//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackupSystem.WindowsService.BackupSystemService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BackupSystemService.IBackupManager")]
    public interface IBackupManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackupManager/CreateScheduleDetails", ReplyAction="http://tempuri.org/IBackupManager/CreateScheduleDetailsResponse")]
        void CreateScheduleDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackupManager/CreateScheduleDetails", ReplyAction="http://tempuri.org/IBackupManager/CreateScheduleDetailsResponse")]
        System.Threading.Tasks.Task CreateScheduleDetailsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBackupManagerChannel : BackupSystem.WindowsService.BackupSystemService.IBackupManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BackupManagerClient : System.ServiceModel.ClientBase<BackupSystem.WindowsService.BackupSystemService.IBackupManager>, BackupSystem.WindowsService.BackupSystemService.IBackupManager {
        
        public BackupManagerClient() {
        }
        
        public BackupManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BackupManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BackupManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BackupManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateScheduleDetails() {
            base.Channel.CreateScheduleDetails();
        }
        
        public System.Threading.Tasks.Task CreateScheduleDetailsAsync() {
            return base.Channel.CreateScheduleDetailsAsync();
        }
    }
}
